### ISSUE TITLE
Compile Ultratools on Ubuntu 15.10

### ISSUE THREAD

**Issue by legluondunet** [Bramas/Ultratools#6]
Hello,

I would like to compile Ultratools on Ubuntu 15.10.
I installed dependencies and fmodapi, like described in the Readme file.
But now, I don't know how to start the compilation, there is no makefile.
Thank you for your help.

LGDN.

**Comment by Bramas** [comment]
Right, you have to generate the make file using qmake from qt.

```
qmake "UltraTools Editor.pro"
```

If qt4 is used instead of qt5 maybe adding the option `-qt=qt5` will work

I forgot to mention it in the readme because I always use qt creator to build it.

Tell me if it works.

**Comment by legluondunet** [comment]
I confirm I can compile UE with qmake method or with QT Creator.
But I think it is better to communicate the qmake way, because you can use checkinstall to make a deb paquet and install it cleanly.
I'm using UE for a long time with wine, but it was very buggy.
With this new native version I hope I could write karaoke songs easier and faster.

Perhaps you could add more details to the readme file, about Linux compilation, like this:

1) Download FMOD EX api here:
http://www.fmod.org/download-previous-products/
and install it:
    tar xvf fmodapi<VERSION_NUMBER>linux.tar.gz
    sudo cp -r fmodapi<VERSION_NUMBER>linux/api/lib/\* /usr/local/lib/.
    sudo mkdir /usr/local/include/fmod/
    sudo cp -r fmodapi<VERSION_NUMBER>linux/api/inc/\* /usr/local/include/fmod/.
    sudo ldconfig

2) Compile Ultratools Editor:
go to the src folder

$ qmake "UltraTools Editor.pro"
$ make
$ sudo make install

**Comment by Bramas** [comment]
Thanks, 
hope everything will work fine :)
